server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

polar:
  geeting: Welcome the the local book catalog!

  testdata2:
    enabled: true

